#!/bin/bash
scp -r \
"../fmriprep/sub-fad1010.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1010-6m.html" \
"../freesurfer/sub-fad1010/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1010/ses-6m/" \
"../fmriprep/sub-fad1010" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1139.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1139-6m.html" \
"../freesurfer/sub-fad1139/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1139/ses-6m/" \
"../fmriprep/sub-fad1139" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1207.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1207-6m.html" \
"../freesurfer/sub-fad1207/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1207/ses-6m/" \
"../fmriprep/sub-fad1207" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1209.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1209-6m.html" \
"../freesurfer/sub-fad1209/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1209/ses-6m/" \
"../fmriprep/sub-fad1209" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1212.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1212-6m.html" \
"../freesurfer/sub-fad1212/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1212/ses-6m/" \
"../fmriprep/sub-fad1212" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1219.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1219-6m.html" \
"../freesurfer/sub-fad1219/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1219/ses-6m/" \
"../fmriprep/sub-fad1219" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1223.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1223-6m.html" \
"../freesurfer/sub-fad1223/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1223/ses-6m/" \
"../fmriprep/sub-fad1223" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1384.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1384-6m.html" \
"../freesurfer/sub-fad1384/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1384/ses-6m/" \
"../fmriprep/sub-fad1384" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1464.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1464-6m.html" \
"../freesurfer/sub-fad1464/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1464/ses-6m/" \
"../fmriprep/sub-fad1464" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad1878.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad1878-6m.html" \
"../freesurfer/sub-fad1878/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad1878/ses-6m/" \
"../fmriprep/sub-fad1878" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad4213.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad4213-6m.html" \
"../freesurfer/sub-fad4213/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad4213/ses-6m/" \
"../fmriprep/sub-fad4213" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad4771.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad4771-6m.html" \
"../freesurfer/sub-fad4771/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad4771/ses-6m/" \
"../fmriprep/sub-fad4771" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad4871.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad4871-6m.html" \
"../freesurfer/sub-fad4871/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad4871/ses-6m/" \
"../fmriprep/sub-fad4871" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad5188.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad5188-6m.html" \
"../freesurfer/sub-fad5188/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad5188/ses-6m/" \
"../fmriprep/sub-fad5188" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad5219.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad5219-6m.html" \
"../freesurfer/sub-fad5219/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad5219/ses-6m/" \
"../fmriprep/sub-fad5219" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep" \
"../fmriprep/sub-fad5540.html" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep/sub-fad5540-6m.html" \
"../freesurfer/sub-fad5540/*" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/freesurfer/sub-fad5540/ses-6m/" \
"../fmriprep/sub-fad5540" "skfk@jude.umd.edu:/data/jude/FAD/fmriprep/fmriprep"
