install.packages("packages/loo_2.7.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/Matrix_1.6-5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/inline_0.3.19.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/QuickJSR_1.1.3.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/RcppEigen_0.3.4.0.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/RcppParallel_5.1.7.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/BH_1.84.0-0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/StanHeaders_2.32.6.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/colourpicker_1.3.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/threejs_0.3.3.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/dygraphs_1.1.1.6.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/shinythemes_1.2.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/Brobdingnag_1.2-9.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rlang_1.1.3.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/scales_1.3.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/vctrs_0.6.5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/lifecycle_1.0.4.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/ggplot2_3.5.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rstan_2.32.5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rstantools_2.4.0.tar.gz", lib = ".", repos = NULL, type = "source")
# install.packages("packages/cmdstan-2.33.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/posterior_1.5.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/cmdstanr_0.7.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/bayesplot_1.11.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/shinystan_2.6.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/bridgesampling_1.1-2.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/nleqslv_3.3.5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages('packages/brms_2.20.4.tar.gz', lib = ".", repos = NULL, type = "source")
library("loo", lib.loc = "./")
library("Matrix", lib.loc = "./")
library("inline", lib.loc = "./")
library("QuickJSR", lib.loc = "./")
library("RcppEigen", lib.loc = "./")
library("RcppParallel", lib.loc = "./")
library("BH", lib.loc = "./")
library("StanHeaders", lib.loc = "./")
library("colourpicker", lib.loc = "./")
library("threejs", lib.loc = "./")
library("dygraphs", lib.loc = "./")
library("shinythemes", lib.loc = "./")
library("Brobdingnag", lib.loc = "./")
library("rlang", lib.loc = "./")
library("scales", lib.loc = "./")
library("vctrs", lib.loc = "./")
library("lifecycle", lib.loc = "./")
library("ggplot2", lib.loc = "./")
library("rstan", lib.loc = "./")
library("rstantools", lib.loc = "./")
# library("cmdstan", lib.loc = "./")
library("posterior", lib.loc = "./")
library("cmdstanr", lib.loc = "./")
library("bayesplot", lib.loc = "./")
library("brms", lib.loc = "./")
