#install.packages("packages/checkmate_2.3.1.tar.gz", lib = ".", repos = NULL, type = "source")
#install.packages("packages/matrixStats_1.3.0.tar.gz", lib = ".", repos = NULL, type = "source")
#install.packages("packages/posterior_1.5.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/loo_2.7.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/Matrix_1.6-5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/inline_0.3.19.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/jsonlite_1.8.8.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/R6_2.5.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/Rcpp_1.0.12.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/QuickJSR_1.1.3.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/RcppEigen_0.3.4.0.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/RcppParallel_5.1.7.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/BH_1.84.0-0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/StanHeaders_2.32.6.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/xfun_0.43.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/knitr_1.46.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rmarkdown_2.26.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/htmltools_0.5.8.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/htmlwidgets_1.6.4.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/colourpicker_1.3.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/threejs_0.3.3.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/dygraphs_1.1.1.6.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/shinythemes_1.2.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/Brobdingnag_1.2-9.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rlang_1.1.3.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/scales_1.3.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/vctrs_0.6.5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/lifecycle_1.0.4.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/ggplot2_3.5.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rstan_2.32.5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rstantools_2.4.0.tar.gz", lib = ".", repos = NULL, type = "source")
# install.packages("packages/cmdstan-2.33.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/cmdstanr_0.7.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/bayesplot_1.11.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/DT_0.33.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/shinystan_2.6.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/bridgesampling_1.1-2.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/nleqslv_3.3.5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages('packages/brms_2.20.4.tar.gz', lib = ".", repos = NULL, type = "source")
#library("checkmate", lib.loc = "./")
#library("matrixStats", lib.loc = "./")
#library("posterior", lib.loc = "./")
library("loo", lib.loc = "./")
library("Matrix", lib.loc = "./")
library("inline", lib.loc = "./")
library("jsonlite", lib.loc = "./")
library("R6", lib.loc = "./")
library("Rcpp", lib.loc = "./")
library("QuickJSR", lib.loc = "./")
library("RcppEigen", lib.loc = "./")
library("RcppParallel", lib.loc = "./")
library("BH", lib.loc = "./")
library("StanHeaders", lib.loc = "./")
library("xfun", lib.loc = "./")
library("knitr", lib.loc = "./")
library("rmarkdown", lib.loc = "./")
library("htmltools", lib.loc = "./")
library("htmlwidgets", lib.loc = "./")
library("colourpicker", lib.loc = "./")
library("threejs", lib.loc = "./")
library("dygraphs", lib.loc = "./")
library("shinythemes", lib.loc = "./")
library("Brobdingnag", lib.loc = "./")
library("rlang", lib.loc = "./")
library("scales", lib.loc = "./")
library("vctrs", lib.loc = "./")
library("lifecycle", lib.loc = "./")
library("ggplot2", lib.loc = "./")
library("rstan", lib.loc = "./")
library("rstantools", lib.loc = "./")
# library("cmdstan", lib.loc = "./")
library("cmdstanr", lib.loc = "./")
library("bayesplot", lib.loc = "./")
library("DT", lib.loc = "./")
library("shinystan", lib.loc = "./")
library("bridgesampling", lib.loc = "./")
library("nleqslv", lib.loc = "./")
library("brms", lib.loc = "./")

library(cmdstanr)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
install_cmdstan(
  dir = "./",
  cores = getOption("mc.cores", mc.cores),
  quiet = FALSE,
  overwrite = FALSE,
  timeout = 1200,
  version = NULL,
  release_url = NULL,
  release_file = "./packages/cmdstan-2.34.1.tgz",
  cpp_options = list(),
  check_toolchain = TRUE,
  wsl = FALSE
)
