install.packages("packages/loo_2.7.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/inline_0.3.19.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/QuickJSR_1.1.3.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/StanHeaders_2.32.6.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/colourpicker_1.3.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/threejs_0.3.3.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/dygraphs_1.1.6.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/shinythemes_1.2.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/Brobdingnag_1.2.9.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rstan_2.32.5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/rstantools_2.4.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/bayesplot_1.11.1.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/shinystan_2.6.0.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/bridgesampling_1.1.2.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages("packages/nleqslv_3.3.5.tar.gz", lib = ".", repos = NULL, type = "source")
install.packages('packages/brms_2.20.4.tar.gz', lib = ".", repos = NULL, type = "source")
library(loo)
library(inline)
library(QuickJSR)
library(StanHeaders)
library(colourpicker)
library(threejs)
library(dygraphs)
library(shinythemes)
library(Brobdingnag)
library(rstan)
library(rstantools)
library(bayesplot)
library(shinystan)
library(bridgesampling)
library(nleqslv)

library(tidyverse)
library(brms)
library(pracma)


